export * from './AuthInterface'
export * from './CampusInterface'
export * from './RegisterAppInterface'
export * from './CampusServicesInterface'
export * from './KidInterface'
export * from './QRSceannerInterface'